import PageObject from "../pageobject/PageObject";
const test_data=require("../fixtures/login_data.json");
describe('Review and Submit module test script for enrollment', () => {
    beforeEach(() => {
        cy.clearLocalStorage();
        cy.login_by_plan_password_and_ssn(test_data.Valid1.plan_password,test_data.Valid1.ssn);
        cy.visit("http://bearypotter.julyservices.local:9030/register/auto-enrollment");
    });
   it('QUI-EN015:Verify Change Election of Your Contribution Election section takes to the Select Contribution Rate page', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        PageObject.reviewandsubmitObj.change_election_button().eq(0).click();
        PageObject.selectcontributerateObj.select_contribute_rate_title_text().should('have.text',"Select Contribution Rate");
   });
   it('QUI-EN016:Verify Next button of Select Contribution Rate page takes back to Final Elections page', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        PageObject.reviewandsubmitObj.change_election_button().eq(0).click();
        PageObject.selectcontributerateObj.pretax_contribution_percentage_input_field().clear().type("4");
        PageObject.selectcontributerateObj.roth_contribution_percentage_input_field().clear().type("5").blur();
        cy.wait(2000);
        PageObject.selectcontributerateObj.next_button().click().click();
        PageObject.finalelectionsObj.final_election_page_title().should('have.text',"Final Elections");
   });
   it('QUI-EN017:Verify Change Election of Your Investment Election section takes to the Choose Your Investment Preference page', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        PageObject.reviewandsubmitObj.change_election_button().eq(1).click();
        PageObject.investmenthomeObj.investment_title().should('have.text',"Choose Your Investment Preference");
   });
   it('QUI-EN018:Verify Select button of any of the option takes to the particular Investment Election page', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        PageObject.reviewandsubmitObj.change_election_button().eq(1).click();
        PageObject.investmenthomeObj.age_based_portfolios_text_link().click();
        PageObject.investmentagebasedObj.age_based_investment_election_title().should('have.text',"Age-Based Investment Election");
   });
   it('QUI-EN019:Verify Next button of Investment Election page takes back to Final Elections page', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        PageObject.reviewandsubmitObj.change_election_button().eq(1).click();
        PageObject.investmenthomeObj.age_based_portfolios_text_link().click();
        PageObject.investmentagebasedObj.election_percentage_input_field().type("100").blur();
        PageObject.investmentagebasedObj.next_button().click();
        PageObject.finalelectionsObj.final_election_page_title().should('have.text',"Final Elections");
   });
   it('QUI-EN020:Verify Change Election of Automatic Investment Rebalance section takes to the Final Elections page', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        PageObject.reviewandsubmitObj.change_election_button().eq(2).click();
        PageObject.finalelectionsObj.final_election_page_title().should('have.text',"Final Elections");
   });
   it('QUI-EN021:Verify Change Election of Automatic Contribution Increase section takes to the Final Elections page', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        cy.wait(2000);
        cy.scrollTo('bottom');
        cy.wait(2000);
        PageObject.reviewandsubmitObj.change_election_button().eq(3).click();
        cy.wait(1000);
        PageObject.finalelectionsObj.final_election_page_title().should('have.text',"Final Elections");
   });
   it('QUI-EN022 and QUI-EN023 :Verify Change Election of Beneficiary Designation section takes to the Final Elections page', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        cy.wait(2000);
        cy.scrollTo('bottom');
        cy.wait(2000);
        PageObject.reviewandsubmitObj.change_election_button().eq(4).click();
        cy.wait(1000);
        PageObject.finalelectionsObj.final_election_page_title().should('have.text',"Final Elections");
        PageObject.finalelectionsObj.next_button().click();
        PageObject.reviewandsubmitObj.review_and_submit_title().should('have.text',"Review and Submit");
   });
   it('QUI-EN024 :Verify that Enrollment survey is completed and Reset Enrollment status', () => {
        PageObject.automaticenrollmentObj.customize_my_enrollment_button().click();
        PageObject.enrollhomeObj.quick_enroll_select_button().click();
        PageObject.starterpackageObj.good_select_button().click();
        cy.wait(2000);
        PageObject.finalelectionsObj.full_name_input_field().clear().type("Tania");
        PageObject.finalelectionsObj.dob_input_field().clear().type("12/31/2000");
        PageObject.finalelectionsObj.relationship_dd_field().select("0: Spouse");
        PageObject.finalelectionsObj.primary_input_field().clear().type("100").blur();
        cy.scrollTo('bottom');
        PageObject.finalelectionsObj.next_button().should('be.enabled').click({force:true});
        cy.wait(2000);
        PageObject.reviewandsubmitObj.submit_button().click();
        cy.wait(6000);
        cy.Reset_Enrollment_Status();
        cy.wait(4000);
   });
   
});
